Add support for user/password auth
heiher/hev-socks5-core pull request #1
Opened 2021-08-13 06:09 UTC by Spider84

2021-08-13 07:00 UTC, heiher requested changes
Thanks for your patch, It might be better if you can make some changes.

BTW, You should to use `clang-format -i src/*` to keep the code style.

2021-08-13 07:00 UTC, heiher commented on src/hev-socks5-client.c
> +        auth.methods[0] = HEV_SOCKS5_AUTH_METHOD_USER;
Although the right way is to send username/password when the server choose authentication, but i think this way is better for help hide protocol.

2021-08-13 07:00 UTC, heiher commented on src/hev-socks5-client.c
> +        strncpy((char *)&auth.methods[2+auth.methods[2]+2], self->base.auth.pass, auth.methods[2+auth.methods[2]+1]);
Use variable-length iovec instead of strncpy?

2021-08-13 07:00 UTC, heiher commented on src/hev-socks5-client.c
> +        iov[0].iov_len += ((2+auth.methods[2]+2)+auth.methods[2+auth.methods[2]+1]);
Initialize at the same time as the data?

```
auth.ver = HEV_SOCKS5_VERSION_5;
auth.method_len = 1;
...
iov[0].iov_base = &auth;
iov[0].iov_len = ...;
```

2021-08-13 07:34 UTC, Spider84 commented on src/hev-socks5-client.c
> +        auth.methods[0] = HEV_SOCKS5_AUTH_METHOD_USER;
This is required by RFC. You know any other methods?

2021-08-13 07:35 UTC, Spider84 commented on src/hev-socks5-client.c
> +        strncpy((char *)&auth.methods[2+auth.methods[2]+2], self->base.auth.pass, auth.methods[2+auth.methods[2]+1]);
?

2021-08-13 07:35 UTC, Spider84 commented on src/hev-socks5-client.c
> +        iov[0].iov_len += ((2+auth.methods[2]+2)+auth.methods[2+auth.methods[2]+1]);
I just trying to save you code-line sequence

2021-08-13 08:38 UTC, heiher commented on src/hev-socks5-client.c
> +        auth.methods[0] = HEV_SOCKS5_AUTH_METHOD_USER;
It seem okay, when the client only provides one method for authentication.

2021-08-13 08:38 UTC, heiher commented on src/hev-socks5-client.c
> +        strncpy((char *)&auth.methods[2+auth.methods[2]+2], self->base.auth.pass, auth.methods[2+auth.methods[2]+1]);
```c
struct iovec iov[6];
int i = 0;

iov[i].iov_base = &auth;
iov[i++].iov_len = 3;

if (self->base.auth.user && self->base.auth.pass) {
    auth.methods[0] = HEV_SOCKS5_AUTH_METHOD_USER;
    auth.methods[1] = HEV_SOCKS5_AUTH_VERSION_1;
    auth.methods[2] = strlen (self->base.auth.user);
    auth.methods[3] = strlen (self->base.auth.pass);
    iov[i].iov_base = self->base.auth.user;
    iov[i++].iov_len = auth.methods[2];
    iov[i].iov_base = &auth.methods[3];
    iov[i++].iov_len = 1;
    iov[i].iov_base = self->base.auth.user;
    iov[i++].iov_len = auth.methods[3];
} else {
    auth.methods[0] = HEV_SOCKS5_AUTH_METHOD_NONE;
}

iov[i].iov_base = &req;
iov[i++].iov_len = 3;
...

memset (&mh, 0, sizeof (mh));
mh.msg_iov = iov;
mh.msg_iovlen = i;
```

2021-08-13 09:11 UTC, Spider84 commented on src/hev-socks5-client.c
> +        auth.methods[0] = HEV_SOCKS5_AUTH_METHOD_USER;
Already - two :) NONE and USER!

2021-08-13 09:13 UTC, Spider84 commented on src/hev-socks5-client.c
> +        strncpy((char *)&auth.methods[2+auth.methods[2]+2], self->base.auth.pass, auth.methods[2+auth.methods[2]+1]);
О_о

2021-08-13 09:23 UTC, heiher commented on src/hev-socks5-client.c
> +        strncpy((char *)&auth.methods[2+auth.methods[2]+2], self->base.auth.pass, auth.methods[2+auth.methods[2]+1]);
The goal is reduce memory copy. ;-D

2021-08-16 15:30 UTC, heiher commented
Merged with amend.

Thank you.

2021-08-16 15:30 UTC, closed without merging